import { Text } from "@/components/retroui/Text";
import { Badge } from "@/components/retroui/Badge";
import { Button } from "@/components/retroui/Button";
import { ArrowRight } from "lucide-react";


const blogPosts = [
    {
        id: 1,
        title: "If You are Not Living Your Best Life, You are Not Living at All",
        date: "17 Aug, 2025",
        category: "LIFESTYLE",
        imageUrl:
            "https://images.unsplash.com/photo-1502691876148-a84978e59af8?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1740",
        slug: "beyond-racetrack-motorsport",
        author: "Abraham Lincoln",
    },
    {
        id: 2,
        title: "The Power of Positive Thinking Is Unmatched",
        date: "02 Aug, 2025",
        category: "HEALTH",
        imageUrl:
            "https://images.unsplash.com/photo-1500964757637-c85e8a162699?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1803",
        slug: "mental-health-breaking-silence",
        author: "Albert Einstein",
    },
    {
        id: 3,
        title: "These Quotes Are Generated by AI",
        date: "29 Jul, 2025",
        category: "ARCHITECTURE",
        imageUrl:
            "https://images.unsplash.com/photo-1546414701-81cc6963c67f?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1844",
        slug: "furniture-style-purpose",
        author: "Sam Altman",
    },
    {
        id: 4,
        title: "The Future of Architecture is Where Technology Meets Creativity",
        date: "15 Jul, 2025",
        category: "ARCHITECTURE",
        imageUrl:
            "https://images.unsplash.com/photo-1620503292890-c597f62cce8d?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=2940",
        slug: "urban-architecture-trends",
        author: "Bill Gates",
    },
    {
        id: 5,
        title: "Humans will always be more creative than AI",
        date: "05 Jun, 2025",
        category: "ARCHITECTURE",
        imageUrl:
            "https://images.unsplash.com/photo-1609530142110-7af0a038c723?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1742",
        slug: "digital-art-revolution",
        author: "David Lynch",
    },
];


export default function BlogSectionSeven() {
    return (
        <section className="py-24 bg-white">
            <div className="container max-w-5xl px-4 mx-auto">
                {/* Masonry Grid */}
                <div className="flex flex-col space-y-8 lg:space-y-6">
                    {blogPosts.map((post) => (
                        <a
                            key={post.id}
                            href={`#${post.slug}`}
                            className="break-inside-avoid flex flex-col lg:flex-row group transition-all"
                        >
                            <div className="relative overflow-hidden w-60 pb-8 lg:pb-0 flex justify-start items-center">
                                <img
                                    src={post.imageUrl}
                                    alt={post.title}
                                    className="h-28 w-40 border-2 shadow-[4px_4px_0_#ffdb33,6px_6px_0_#000] rounded-md"
                                />
                            </div>
                            <div className="lg:p-6 flex-1">
                                <Badge size="sm" variant="solid" className="rounded-sm outline">
                                    {post.category}
                                </Badge>
                                <Text
                                    as="h3"
                                    className="mb-1 mt-4 font-sans"
                                >
                                    {post.title}
                                </Text>
                                <div className="flex space-x-2">
                                    <Text className="text-sm">By <span className="font-medium">{post.author}</span></Text>
                                    <Text className="text-sm">⋅</Text>
                                    <Text className="text-sm">{post.date}</Text>
                                </div>
                            </div>

                            <div className="hidden lg:flex w-24 justify-end items-center">
                                <Button className="rounded-md py-2 group-hover:shadow-sm group-hover:translate-y-1 group-hover:translate-x-1" size="sm">
                                    <ArrowRight className="w-4 h-4" />
                                </Button>
                            </div>
                        </a>
                    ))}
                </div>
            </div>
        </section>
    );
}